### ISSUE TITLE
I2C Timeout - M5stack cores3

### ISSUE THREAD

**Issue by gedeondt** [adafruit/Adafruit_CircuitPython_FocalTouch#33]
Hi,

   I am having a weird issue with this device.

   First I had to add a new vendor:

       if vend_id not in (0x11, 0x42, 0x01, **0x02)**:

  Second, I have multiple ETIMEDOUT.

  Sounds like a bug or a hardware problem?

**Comment by slootsky** [comment]
Similar for me with the m5stack dial.

Sometimes I get the following errors
[Errno 116] ETIMEDOUT
[Errno 19] No such device

And then sometimes my program won't restart (from ctrl+d at prompt)
Traceback (most recent call last):
  File "code.py", line 15, in <module>
  File "macro_key_with_display.py", line 201, in <module>
  File "adafruit_focaltouch.py", line 95, in __init__
RuntimeError: Did not find FT chip
